In [2]:
import numpy as np

In [3]:
filepath = "/cluster/home/wueestm/f3loc/evol_path/hge_customized_complete/depthanything_72traj_len_100_dt_1_vits_eval_02/pretty_filter_extended/results.pkl"

results = np.load(filepath, allow_pickle=True)

In [5]:
results.keys()

dict_keys(['per_frame', 'per_seq', 'overall'])

In [6]:
results["overall"].keys()

dict_keys(['mean_mean_depth_MAE', 'mean_mean_depth_cos_sim', 'mean_mean_ray_MAE', 'mean_mean_obs_pos_err', 'mean_mean_obs_orn_err', 'mean_mean_post_pos_err', 'mean_mean_post_orn_err', 'mean_recalls', 'mean_successes', 'mean_RMSEs'])

In [8]:
results["overall"]["mean_successes"]

array([0.81818182, 0.18181818, 0.        , 0.        ])

In [9]:
results["overall"]["mean_RMSEs"]

2.954063898564789

In [11]:
results["per_seq"]["RMSEs_all_ls"]

[array(0.40779285),
 array(28.00595606),
 array(0.44195249),
 array(0.24645948),
 array(0.4653098),
 array(0.48281938),
 array(0.43218166),
 array(0.61121901),
 array(0.28631158),
 array(0.65880501),
 array(0.45589556)]

In [14]:
results["per_seq"].keys()

dict_keys(['mean_depth_MAE_ls', 'mean_depth_cos_sim_ls', 'mean_ray_MAE_ls', 'mean_obs_pos_err_ls', 'mean_obs_orn_err_ls', 'mean_post_pos_err_ls', 'mean_post_orn_err_ls', 'recalls_all_ls', 'successes_all_ls', 'RMSEs_all_ls'])

In [18]:
results["per_seq"]["successes_all_ls"][:][0]

array([ True, False, False, False])

In [20]:
results["per_seq"]["successes_all_ls"]

[array([ True, False, False, False]),
 array([False, False, False, False]),
 array([ True, False, False, False]),
 array([ True,  True, False, False]),
 array([ True, False, False, False]),
 array([ True, False, False, False]),
 array([ True, False, False, False]),
 array([False, False, False, False]),
 array([ True,  True, False, False]),
 array([ True, False, False, False]),
 array([ True, False, False, False])]

In [21]:
results["per_seq"]["successes_all_ls"]

TypeError: list indices must be integers or slices, not tuple

In [24]:
results["per_seq"]["RMSEs_all_ls"]

[array(0.40779285),
 array(28.00595606),
 array(0.44195249),
 array(0.24645948),
 array(0.4653098),
 array(0.48281938),
 array(0.43218166),
 array(0.61121901),
 array(0.28631158),
 array(0.65880501),
 array(0.45589556)]

In [26]:
import numpy as np

# Original array of values
values = [
    np.array(0.40779285),
    #np.array(28.00595606),
    np.array(0.44195249),
    np.array(0.24645948),
    np.array(0.4653098),
    np.array(0.48281938),
    np.array(0.43218166),
    #np.array(0.61121901),
    np.array(0.28631158),
    np.array(0.65880501),
    np.array(0.45589556)
]

# Convert to a single numpy array and calculate the mean
mean_value = np.mean(values)

print("Mean:", mean_value)


Mean: 0.43083642333333333


In [ ]:
print("mean RMSE succeeded : ", RMSEs[success_10].mean())